import Image from "next/image";
import AboutUs from "../Componentr/AboutUs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <AboutUs />
    </>
  );
}
